// main handles the root command and its associated subcommands defined in other files
package main

import (
	"os"

	"github.com/ethanbaker/note/pkg/note"
	"github.com/spf13/cobra"
)

// Helper function to handle errors generated by the program. Errors are propagated and
// printed to the user and then the program exits unsuccessfully
func errHandler(cmd *cobra.Command, err error) {
	if err != nil {
		cmd.PrintErr(err.Error())
		cmd.Println()
		os.Exit(1)
	}
}

func main() {
	// Suppress logs
	note.SuppressLogs()

	// Create new root command
	cmd := &cobra.Command{
		Use:   "note",
		Short: "Note & note management CLI tool",
		Long:  "A command-line tool to manage notes, notes, and configurations",
		CompletionOptions: cobra.CompletionOptions{
			DisableDefaultCmd: true,
		},
	}

	// Add subcommands
	cmd.AddCommand(newCmd)
	cmd.AddCommand(editCmd)
	cmd.AddCommand(removeCmd)
	cmd.AddCommand(listCmd)
	cmd.AddCommand(configCmd)
	cmd.AddCommand(infoCmd)
	cmd.AddCommand(publishCmd)

	// Add autocompletion support
	cmd.CompletionOptions.DisableDefaultCmd = false

	// Run the command
	if err := cmd.Execute(); err != nil {
		os.Exit(1)
	}
}
